---
  - name: install httpd for Centos
    yum: name=httpd state=present
    when: ansible_distribution == 'CentOS'


  - name: Copy index.html
    copy: src=index.html dest=/var/www/html/index.html backup=yes
    when: ansible_distribution == 'CentOS'

  - name: Copy index config
    template: src=index.html.j2 dest=/var/www/html/template.html
    notify: restart webserver
