---
  - name: install httpd service
    yum: name=httpd state=installed
  - name: start the http server
    service: name=httpd state=started
  - name: copy
    copy: src=index.html dest=/var/www/html/index.html
